trigger:
- main

resources:
- repo: self

variables:
  # 1. Name of the Docker Hub connection you created in Azure DevOps Settings
  dockerRegistryServiceConnection: 'dockerhub-conn'
  
  # 2. Your Docker Hub username + repository name
  repositoryName: 'manjuns2012/my_repo'
  
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)' # Log in using your service connection
        repository: '$(repositoryName)'                          # Where to store it in Docker Hub
        command: 'buildAndPush'                                  # Build AND upload it
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        tags: |
          $(tag)
          latest